### ISSUE TITLE
onscroll causes all elements on page to disappear. 

### ISSUE THREAD

**Issue by Jnull** [lukecfairchild/FB-Cleanup#1]
why are there two scroll listeners? and so many static parentNode references?

**Comment by lukecfairchild** [comment]
Because they both do different things, so its better to separate the functionality. Especially if we add things like options down the road or split up the functionality further. The parentNode reference is to avoid facebooks heavy obfuscation, I would like to refine this more so its dynamic, but this is just a first draft.

**Comment by Jnull** [comment]
oh alright, i was thinking of a broader ad blocker that would scale to other sites.  I'm concerned that Facebook will change in the future and break everything. Maybe considering using/creating the east list from adblock plus:  https://easylist-downloads.adblockplus.org/easylist.txt  ?

**Comment by lukecfairchild** [comment]
i am using adblock, and it doesnt block it. The issue with facebook is you cant reliably use css locators, which afaik is what adblock uses.

**Comment by Jnull** [comment]
For the last month I've been working on a css block using xpath and the elementFromPoint function to store in localStorage.

**Comment by lukecfairchild** [comment]
xpaths arent reliable with facebook either. And in general arent reliable.

**Comment by Jnull** [comment]
want to try my demo? it's pretty reliable.

**Comment by lukecfairchild** [comment]
version 1.0.3 fixed the deleting all posts.

**Comment by Jnull** [comment]
WooHoo!
